### ISSUE TITLE
Crashes when select a user

### ISSUE THREAD

**Issue by Geoff55** [tfonfara/RemoteForTautulli-Issues#2] opened 2018-06-28 12:11 UTC
### New Issue Checklist

- [x] My issue is related to the [Remote for Tautulli](https://itunes.apple.com/app/id1343177312) app, report issues for Tautulli [here](https://github.com/Tautulli/Tautulli-Issues/issues)
- [x] I updated Remote for Tautulli to the latest version
- [ x] I searched for [existing GitHub issues](https://github.com/tfonfara/RemoteForTautulli-Issues/issues

[I have the remote for Tautulli installed on both my iPhone and iPad.  The iPhone has no issues.  On the iPad if I select a specific user from the User section the app crashes.  I have 3 users - 2 are fine but one continually crashes when selected, but it doesn't crash on the iPhone.  Ipad is a generation 4 running latest iOS.]

### Steps to Reproduce

1. [Reproducing is not a problem - does it every time.  I have tried uninstalling and reinstalling the app but it makes no difference.]

**Expected behavior:** [The app displays information about the user.]

**Actual behavior:** [App crashes]

**Reproduces how often:** [Every time]

### Environment

* Device: iPad generation 4
* OS version: latest version
* App version: latest version
* Tautulli version: latest version

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Geoff55** [comment] 2018-06-28 13:46
Hi

 

I selected the User again after a track by Emerson, Lake and Palmer started playing.

 

The log is attached.

 

I am also experiencing a second, separate issue.  Then I select Libraries from More I get an error box – “Error occurred while loading data.  Please try again later or inspect your Tautulli Server Logs.”

 

Best Wishes

 

Geoff

**Comment by tfonfara** [comment] 2018-06-29 09:44
Unfortunately I cannot reproduce any of the two issues, everything is working fine. Also I didn't receive any crash logs from any other user so far. Maybe there's something misconfigured in your setup?

Logs were not attached, but please upload your log files from more > settings > top right button and paste the number you'll get here.

**Comment by Geoff55** [comment] 2018-06-29 12:42
Hi

Thanks for your reply.

I have uploaded the logs - the number given is - 95032.

The two issues were experienced just prior to uploading.

Best Wishes

Geoff

**Comment by tfonfara** [comment] 2018-06-30 10:38
Regarding libraries error: I can see you're trying to connect to a local ip address and this request ended up in error 400. Seems that there's something not correct configured in your system.

Regarding the crash unfortunately I'm still unable to reproduce it and also still no other user experienced that crash 😕if you don't play anything does it also crash? If you open details for another user, does is also crash?

**Comment by tfonfara** [comment] 2018-07-03 09:51
I just tested the app with exactly your setup (iPad 4, iOS 10.3.3) and cannot find any issue, neither the crash in users nor the the libraries error. It has to be something server related 😕
Maybe it would be possible to give me temporary access to the server if it's external reachable so I can have a deeper look and debug the application to find out what causes the issues? A screenshot of a qr code (please scan the qr code after screenshotting so it gets registered) would be enough I think. But in this case we should this discussion to email, please don't paste that here.

**Comment by Geoff55** [comment] 2018-07-03 13:12
That would be fine.  What email address would I use to send the QR code?

Thanks

**Comment by tfonfara** [comment] 2018-07-03 13:56
Cool, thanks! In the app if you go to more > contact an email composer will open.

**Comment by tfonfara** [comment] 2018-07-07 07:47
Fixed with v1.3.2.

**Closed by tfonfara** 2018-07-07 07:47 UTC
Labels: bug, fixed-next-release
